---
## HOMELAB-WIDE VARIABLES
gitops_user: "lab"
gitops_tz: "UTC"

backup_runner_user: "allan"
backup_runner_remote_host: "{{ hostvars['pennywise'].ansible_host }}"
backup_runner_remote_base_path: "/mnt/pool1/allans-home-lab/backups-automated/{{ inventory_hostname }}"
default_remote_nas_per_host_backup_volume: "{{ backup_runner_user }}@{{ backup_runner_remote_host }}:{{ backup_runner_remote_base_path }}"

git_author_name: "Allan Lewis"
git_author_email: "allan@allanshomelab.com"

## ANSIBLE BUILT-IN VARIABLES
ansible_python_interpreter: "/usr/bin/python3"
ansible_user: "{{ gitops_user }}"

## OS CONVERGENCE FLAGS
converge_arch: "{{ ansible_distribution == 'Archlinux' }}"
converge_nixos: "{{ ansible_distribution == 'NixOS' }}"
converge_ubuntu: "{{ ansible_distribution == 'Ubuntu' }}"

## CONVERGENCE FEATURE FLAGS
feature_flag_aws: false
feature_flag_devops: false
feature_flag_node_exporter: false
feature_flag_openvpn: false
feature_flag_s3_mirror: false
feature_flag_tailscale: false

converge_docker: false
converge_docker_monitoring: false
converge_postgres_dump: false
converge_restore: false
converge_openvpn: false
converge_docker_pihole: false
converge_docker_twingate: false
