---
converge_devops: true

doppler_user: "lab"

nixos_converge_prepare_dirs_devops:    
  - path: "/var/lib/homelab-secrets/doppler"
    owner: "lab"
    group: "lab"
    mode: "0755"
  - path: "/var/lib/homelab-secrets/ssh/lab"
    owner: "lab"
    group: "lab"
    mode: "0700"

nixos_converge_prepare_keys_devops: ["lab"]

nixos_required_variables_devops:
  - aws_default_region
  - aws_access_key_id
  - aws_secret_access_key
  - doppler_service_token
