---
converge_docker: true

nixos_docker_service_configs:
  it_tools:
    compose_app_name: tools
    compose_source_type: file
    compose_file_src: files/it-tools.compose.yaml
  homepage:
    compose_app_name: homepage
    compose_source_type: template
    compose_template_src: "templates/homepage.compose.yaml.j2"
    compose_extra_templates:
      - src: "templates/homepage/bookmarks.yaml.j2"
        dest: "/etc/homepage/bookmarks.yaml"
      - src: "templates/homepage/docker.yaml.j2"
        dest: "/etc/homepage/docker.yaml"
      - src: "templates/homepage/services.yaml.j2"
        dest: "/etc/homepage/services.yaml"
      - src: "templates/homepage/settings.yaml.j2"
        dest: "/etc/homepage/settings.yaml"
      - src: "templates/homepage/widgets.yaml.j2"
        dest: "/etc/homepage/widgets.yaml"
  jellyfin:
    compose_app_name: jellyfin
    compose_source_type: template
    compose_template_src: templates/jellyfin.compose.yaml.j2
    compose_env:
      JELLYFIN_PUBLISHED_URL: "https://jellyfin.media.allanshomelab.com"
      JELLYFIN_USER_UID: "{{ lab_uid }}"
      JELLYFIN_GROUP_GID: "{{ lab_gid }}"
  monitoring:
    compose_app_name: monitoring
    compose_source_type: template
    compose_template_src: "templates/monitoring.compose.yaml.j2"
  nginx:
    compose_app_name: nginx
    compose_source_type: file
    compose_file_src: files/nginx.compose.yaml
  no_geeks_brewing:
    compose_app_name: no_geeks_brewing
    compose_source_type: file
    compose_file_src: files/no_geeks_brewing.compose.yaml
    compose_env:
      NO_GEEKS_BREWING_AUTHENTIK_CLIENT_ID:  "{{ lookup('env', 'NO_GEEKS_BREWING_AUTHENTIK_CLIENT_ID') }}"
      NO_GEEKS_BREWING_AUTHENTIK_CLIENT_SECRET: "{{ lookup('env', 'NO_GEEKS_BREWING_AUTHENTIK_CLIENT_SECRET') }}"
      NO_GEEKS_BREWING_AUTHENTIK_ISSUER_URL: "{{ lookup('env', 'NO_GEEKS_BREWING_AUTHENTIK_ISSUER_URL') }}"
      NO_GEEKS_BREWING_BREWFATHER_AUTH_TOKEN: "{{ lookup('env', 'NO_GEEKS_BREWING_BREWFATHER_AUTH_TOKEN') }}"
      NO_GEEKS_BREWING_POST_LOGOUT_REDIRECT_URI: "{{ lookup('env', 'NO_GEEKS_BREWING_POST_LOGOUT_REDIRECT_URI') }}"
      NO_GEEKS_BREWING_AUTHENTIK_LOGOUT_URI: "{{ lookup('env', 'NO_GEEKS_BREWING_AUTHENTIK_LOGOUT_URI') }}"
      NO_GEEKS_BREWING_REDIRECT_URI: "{{ lookup('env', 'NO_GEEKS_BREWING_REDIRECT_URI') }}"
  portainer:
    compose_app_name: portainer
    compose_source_type: template
    compose_template_src: "templates/portainer.compose.yaml.j2"
  rstack:
    compose_app_name: rstack
    compose_source_type: template
    compose_template_src: templates/rstack.compose.yaml.j2
  trilium:
    compose_app_name: trilium
    compose_source_type: template
    compose_template_src: "templates/trilium.compose.yaml.j2"
  twingate:
    compose_app_name: twingate
    compose_source_type: template
    compose_template_src: "templates/twingate.compose.yaml.j2"
    compose_env:
      TWINGATE_NETWORK_NAME: "{{ lookup('env', 'TWINGATE_NETWORK_NAME') }}"
      TWINGATE_ACCESS_TOKEN: "{{ twingate_access_token }}"
      TWINGATE_REFRESH_TOKEN: "{{ twingate_refresh_token }}"
  vaultwarden:    
    compose_app_name: vaultwarden
    compose_source_type: template
    compose_template_src: templates/vaultwarden.compose.yaml.j2
    compose_env: 
      ADMIN_TOKEN:  "{{ lookup('env', 'VAULTWARDEN_ADMIN_TOKEN') }}"
      SIGNUPS_ALLOWED: "false"
