---
converge_docker: true

immich_version: "v2.5.6"

nixos_docker_service_configs:
  authentik:
    compose_app_name: authentik
    compose_source_type: url
    compose_url: "https://docs.goauthentik.io/compose.yml"
    compose_env:
      AUTHENTIK_TAG: "{{ authentik_version }}"
      COMPOSE_PORT_HTTP: 9180
      COMPOSE_PORT_HTTPS: 9143
      PG_PASS: "{{ lookup('env', 'DOCKER_AUTHENTIK_PG_PASS') }}"
      AUTHENTIK_SECRET_KEY: "{{ lookup('env', 'DOCKER_AUTHENTIK_SECRET_KEY') }}"
  cloudflare:
    compose_app_name: cloudflare
    compose_source_type: file
    compose_file_src: files/cloudflare.compose.yaml
    compose_env:
      CLOUDFLARE_TUNNEL_TOKEN: "{{ lookup('env','CLOUDFLARE_TUNNEL_TOKEN') }}"
  it_tools:
    compose_app_name: tools
    compose_source_type: file
    compose_file_src: files/it-tools.compose.yaml
  gatus:
    compose_app_name: gatus
    compose_source_type: template
    compose_template_src: "templates/gatus.compose.yaml.j2"
    compose_extra_templates:
      - src: "templates/gatus/gatus.config.yaml.j2"
        dest: "/etc/gatus/config.yaml"
  homepage:
    compose_app_name: homepage
    compose_source_type: template
    compose_template_src: "templates/homepage.compose.yaml.j2"
    compose_extra_templates:
      - src: "templates/homepage/bookmarks.yaml.j2"
        dest: "/etc/homepage/bookmarks.yaml"
      - src: "templates/homepage/docker.yaml.j2"
        dest: "/etc/homepage/docker.yaml"
      - src: "templates/homepage/services.yaml.j2"
        dest: "/etc/homepage/services.yaml"
      - src: "templates/homepage/settings.yaml.j2"
        dest: "/etc/homepage/settings.yaml"
      - src: "templates/homepage/widgets.yaml.j2"
        dest: "/etc/homepage/widgets.yaml"
  immich:
    compose_app_name: immich
    compose_source_type: url
    compose_url: "https://github.com/immich-app/immich/releases/download/{{ immich_version }}/docker-compose.yml"
    compose_env:
      IMMICH_VERSION: "{{ immich_version }}"
      UPLOAD_LOCATION: "/data/immich"
      DB_DATA_LOCATION: "/srv/immich/postgres"  
      REDIS_DATA_LOCATION: "/srv/immich/redis"
      MODEL_CACHE_LOCATION: "/srv/immich/model-cache"
      COMPOSE_PROJECT_NAME: "immich"
      DB_USERNAME: "postgres"
      DB_DATABASE_NAME: "immich"
      DB_PASSWORD: "{{ lookup('env', 'IMMICH_DB_PASSWORD') }}"
  jellyfin:
    compose_app_name: jellyfin
    compose_source_type: template
    compose_template_src: templates/jellyfin.compose.yaml.j2
    compose_env:
      JELLYFIN_PUBLISHED_URL: "https://jellyfin.media.allanshomelab.com"
      JELLYFIN_USER_UID: "{{ lab_uid }}"
      JELLYFIN_GROUP_GID: "{{ lab_gid }}"
  monitoring:
    compose_app_name: monitoring
    compose_source_type: template
    compose_template_src: "templates/monitoring.compose.yaml.j2"
  nginx:
    compose_app_name: nginx
    compose_source_type: file
    compose_file_src: files/nginx.compose.yaml
  no_geeks_brewing:
    compose_app_name: no_geeks_brewing
    compose_source_type: file
    compose_file_src: files/no_geeks_brewing.compose.yaml
    compose_env:
      NO_GEEKS_BREWING_AUTHENTIK_CLIENT_ID:  "{{ lookup('env', 'NO_GEEKS_BREWING_AUTHENTIK_CLIENT_ID') }}"
      NO_GEEKS_BREWING_AUTHENTIK_CLIENT_SECRET: "{{ lookup('env', 'NO_GEEKS_BREWING_AUTHENTIK_CLIENT_SECRET') }}"
      NO_GEEKS_BREWING_AUTHENTIK_ISSUER_URL: "{{ lookup('env', 'NO_GEEKS_BREWING_AUTHENTIK_ISSUER_URL') }}"
      NO_GEEKS_BREWING_BREWFATHER_AUTH_TOKEN: "{{ lookup('env', 'NO_GEEKS_BREWING_BREWFATHER_AUTH_TOKEN') }}"
      NO_GEEKS_BREWING_POST_LOGOUT_REDIRECT_URI: "{{ lookup('env', 'NO_GEEKS_BREWING_POST_LOGOUT_REDIRECT_URI') }}"
      NO_GEEKS_BREWING_AUTHENTIK_LOGOUT_URI: "{{ lookup('env', 'NO_GEEKS_BREWING_AUTHENTIK_LOGOUT_URI') }}"
      NO_GEEKS_BREWING_REDIRECT_URI: "{{ lookup('env', 'NO_GEEKS_BREWING_REDIRECT_URI') }}"
  observability:
    compose_app_name: observability
    compose_source_type: template
    compose_template_src: templates/observability.compose.yaml.j2
    compose_env:
      GF_SERVER_DOMAIN: "grafana.allanshomelab.com"
      GF_SERVER_ROOT_URL: "https://grafana.allanshomelab.com"
      GF_SERVER_ENABLE_GZIP: true
      GF_SECURITY_ADMIN_USER: "{{ lookup('env', 'HOMEPAGE_VAR_GRAFANA_USERNAME') }}"
      GF_SECURITY_ADMIN_PASSWORD: "{{ lookup('env', 'HOMEPAGE_VAR_GRAFANA_PASSWORD') }}"
      GF_SECURITY_DISABLE_GRAVATAR: true
      GF_SECURITY_COOKIE_SECURE: true
      GF_SECURITY_COOKIE_SAMESITE: lax
      GF_USERS_ALLOW_SIGN_UP: false
      GF_USERS_AUTO_ASSIGN_ORG: true
      GF_USERS_AUTO_ASSIGN_ORG_ROLE: Viewer
      GF_AUTH_DISABLE_LOGIN_FORM: false
      GF_AUTH_BASIC_ENABLED: true
      GF_AUTH_ANONYMOUS_ENABLED: false
      GF_PANELS_DISABLE_SANITIZE_HTML: true
      GF_EXPLORE_ENABLED: true
      GF_ALERTING_ENABLED: true
      GF_UNIFIED_ALERTING_ENABLED: true
      GF_LOG_MODE: console
      GF_LOG_LEVEL: info
      GF_INSTALL_PLUGINS: "grafana-piechart-panel"
      # Generic OAuth (Authentik)
      GF_AUTH_GENERIC_OAUTH_ENABLED: true
      GF_AUTH_GENERIC_OAUTH_NAME: Authentik
      GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP: true
      GF_AUTH_GENERIC_OAUTH_SCOPES: "openid profile email"
      GF_AUTH_GENERIC_OAUTH_AUTH_URL: "https://authn.allanshomelab.com/application/o/authorize/"
      GF_AUTH_GENERIC_OAUTH_TOKEN_URL: "https://authn.allanshomelab.com/application/o/token/"
      GF_AUTH_GENERIC_OAUTH_API_URL: "https://authn.allanshomelab.com/application/o/userinfo/"
      GF_AUTH_GENERIC_OAUTH_NAME_ATTRIBUTE_PATH: preferred_username
      GF_AUTH_GENERIC_OAUTH_EMAIL_ATTRIBUTE_PATH: email
      GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: "contains(groups[*], 'grafana-admin') && 'Admin' || 'Viewer'"
      GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "{{ lookup('env', 'GF_AUTH_GENERIC_OAUTH_CLIENT_ID') }}"
      GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "{{ lookup('env', 'GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET') }}"
    # 472 is the default user id for the grafana container
    compose_extra_templates:
      - src: "templates/observability/grafana-datasource.yaml.j2"
        dest: "/etc/grafana/provisioning/datasources/prometheus.yaml"
        uid: "472"
        gid: "472"
      - src: "templates/observability/alertmanager.yaml.j2"
        dest: "/etc/alertmanager/alertmanager.yml"
      - src: "templates/observability/telegram.tmpl.j2"
        dest: "/etc/alertmanager/config/telegram.tmpl"
      - src: "templates/observability/prometheus.yaml.j2"
        dest: "/etc/prometheus/prometheus.yml"
      - src: "templates/observability/rules.yaml.j2"
        dest: "/etc/prometheus/rules.yml"
  plex: 
    compose_app_name: plex
    compose_source_type: template
    compose_template_src: templates/plex.compose.yaml.j2
  portainer:
    compose_app_name: portainer
    compose_source_type: template
    compose_template_src: "templates/portainer.compose.yaml.j2"
  rstack:
    compose_app_name: rstack
    compose_source_type: template
    compose_template_src: templates/rstack.compose.yaml.j2
  tautulli:
    compose_app_name: tautulli
    compose_source_type: template
    compose_template_src: templates/tautulli.compose.yaml.j2
  traefik:
    compose_app_name: traefik
    compose_source_type: template
    compose_template_src: "templates/traefik.compose.yaml.j2"
    compose_env:
      CLOUDFLARE_EMAIL: "allan.e.lewis@gmail.com"
      CLOUDFLARE_API_KEY: "{{ lookup('env', 'TRAEFIK_CF_API_KEY') }}"
    compose_extra_templates:
      - src: "templates/traefik/traefik.config.yaml.j2"
        dest: "/etc/traefik/traefik.yaml"
        uid: "{{ lab_uid }}"
        gid: "{{ lab_gid }}"
  trilium:
    compose_app_name: trilium
    compose_source_type: template
    compose_template_src: "templates/trilium.compose.yaml.j2"
  twingate:
    compose_app_name: twingate
    compose_source_type: template
    compose_template_src: "templates/twingate.compose.yaml.j2"
    compose_env:
      TWINGATE_NETWORK_NAME: "{{ lookup('env', 'TWINGATE_NETWORK_NAME') }}"
      TWINGATE_ACCESS_TOKEN: "{{ twingate_access_token | default('') }}"
      TWINGATE_REFRESH_TOKEN: "{{ twingate_refresh_token | default('') }}"
  vaultwarden:    
    compose_app_name: vaultwarden
    compose_source_type: template
    compose_template_src: templates/vaultwarden.compose.yaml.j2
    compose_env: 
      ADMIN_TOKEN:  "{{ lookup('env', 'VAULTWARDEN_ADMIN_TOKEN') }}"
      SIGNUPS_ALLOWED: "false"
