ansible_python_interpreter: /run/current-system/sw/bin/python3

backup_runner_rsync_flags: "-aHAX --numeric-ids --delete-delay --partial --partial-dir=.rsync-partial --human-readable --sparse --mkpath"

