---
converge_docker: true
converge_docker_monitoring: true
converge_devops: true
converge_node_exporter: true

doppler_user: "lab"

nixos_converge_dirs_devops:
  - path: "/var/lib/homelab-secrets/ssh/lab"
    owner: "lab"
    group: "lab"
    mode: "0700"
