---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Home Lab Management:
    - Gilead:
        icon: truenas.png
        href: https://gilead.hosts.allanshomelab.com
        description: NAS (offsite backup)
        widget:
            type: truenas
            url: https://gilead.hosts.allanshomelab.com
            username: truenas_admin
            password: "{{HOMEPAGE_VAR_TRUENAS_PASSWORD}}"
    - Derry:
        icon: asustor.png
        href: https://derry.hosts.allanshomelab.com
        description: NAS (local backup)
    - Maturin:
        icon: proxmox.png
        href: https://maturin.hosts.allanshomelab.com
        description: Hypervisor
        widget:
            type: proxmox
            url: https://maturin.hosts.allanshomelab.com
            username: "{{HOMEPAGE_VAR_MATURIN_USERNAME}}"
            password: "{{HOMEPAGE_VAR_MATURIN_PASSWORD}}"
            fields: ['vms', 'resources.cpu', 'resources.mem']
    - Pennywise:
        icon: truenas.png
        href: https://pennywise.hosts.allanshomelab.com
        description: NAS
        widget:
            type: truenas
            url: https://pennywise.hosts.allanshomelab.com
            username: truenas_admin
            password: "{{HOMEPAGE_VAR_TRUENAS_PASSWORD}}"

- Dev Ops:
    - Alertmanager:
        icon: alertmanager.png
        href: https://alertmanager.nixos.allanshomelab.com
        description: Monitoring system
    - Gatus:
        icon: gatus.png
        href: https://gatus.nixos.allanshomelab.com
        description: Health dashboard
        widget:
            type: gatus
            url: https://gatus.nixos.allanshomelab.com
    - Grafana:
        icon: grafana.png
        href: https://grafana.allanshomelab.com
        description: Operational dashboards
        widget:
            type: grafana
            url: https://grafana.allanshomelab.com
            username: "{{HOMEPAGE_VAR_GRAFANA_USERNAME}}"
            password: "{{HOMEPAGE_VAR_GRAFANA_PASSWORD}}"
            fields: ['dashboards', 'datasources']
    - Prometheus:
        icon: prometheus.png
        href: https://prometheus.nixos.allanshomelab.com
        description: Monitoring/alerting toolkit
        widget:
            type: prometheus
            url: https://prometheus.nixos.allanshomelab.com

- Networking and Authentication:
    - Authentik:
        icon: authentik.png
        href: https://authn.allanshomelab.com
        description: Identity provider
        widget:
            type: authentik
            url: https://authn.allanshomelab.com
            key: "{{HOMEPAGE_VAR_AUTHENTIK_KEY_DOCKER}}"
            version: 2
    - Cloudflared:
        icon: cloudflare.png
        href: "{{HOMEPAGE_VAR_CLOUDFLARE_URL}}"
        description: Zero trust tunnel
        widget:
            type: cloudflared
            key: "{{HOMEPAGE_VAR_CLOUDFLARE_KEY}}"
            accountid: "{{HOMEPAGE_VAR_CLOUDFLARE_ACCOUTNT_ID}}"
            tunnelid: "{{HOMEPAGE_VAR_CLOUDFLARE_TUNNEL_ID}}"
    - Nginx:
        icon: nginx.png
        href: https://nginx.docker.allanshomelab.com
        description: Web server
    - Pi-hole:
        icon: pi-hole.png
        href: https://dns.nixos.allanshomelab.com
        description: Backup DNS server
        widget:
            type: pihole
            url: https://dns.nixos.allanshomelab.com
            version: 6
            key: "{{HOMEPAGE_VAR_PIHOLE_KEY_DOCKER}}"
    - Tailscale:
        icon: tailscale.png
        href: https://login.tailscale.com/admin/machines
        description: Mesh VPN
    - Traefik:
        icon: traefik.png
        href: https://traefik.nixos.allanshomelab.com
        description: Reverse proxy/load balancer
        widget:
            type: traefik
            url: https://traefik.nixos.allanshomelab.com
    - Twingate:
        icon: twingate.png
        href: https://allanshomelab.twingate.com/networks/overview
        description: Zero-trust access
