---
- name: Ensure that remote directories exist
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    mode: "{{ item.mode | default('0755') }}"
  with_items:
    - path: "{{ nixos_dir }}/hosts/{{ inventory_hostname }}"
    - path: "/run/secrets"

- name: Capture tailscale auth key from environment
  no_log: true
  ansible.builtin.set_fact:
    tailscale_authkey: "{{ lookup('env', 'TAILSCALE_AUTHKEY') | trim }}"
  when: converge_tailscale | bool

- name: Fail if key missing
  ansible.builtin.fail:
    msg: "TAILSCALE_AUTHKEY env var is not set"
  when:
    - converge_tailscale | bool
    - tailscale_authkey | length == 0

- name: Write tailscale auth key file
  become: true
  no_log: true
  ansible.builtin.copy:
    dest: /run/secrets/tailscale-authkey
    content: "{{ tailscale_authkey }}"
    owner: root
    group: root
    mode: "0400"
  when: converge_tailscale | bool

- name: Check if host-local hardware config exists in flake dir
  ansible.builtin.stat:
    path: "/etc/nixos-flakes/hosts/{{ inventory_hostname }}/hardware-configuration.nix"
  register: hw_in_flake
  changed_when: false

- name: Generate hardware-configuration.nix into flake dir (only if missing)
  ansible.builtin.command: >
    /run/current-system/sw/bin/nixos-generate-config
    --show-hardware-config
  register: hw_out
  when: not hw_in_flake.stat.exists
  changed_when: true

- name: Write hardware-configuration.nix into flake dir (only if missing)
  ansible.builtin.copy:
    dest: "/etc/nixos-flakes/hosts/{{ inventory_hostname }}/hardware-configuration.nix"
    content: "{{ hw_out.stdout }}\n"
    owner: root
    group: root
    mode: "0644"
  when: not hw_in_flake.stat.exists

- name: Copy all NixOS modules to host
  ansible.builtin.copy:
    src: "files/modules"
    dest: "{{ nixos_dir }}"
    owner: root
    group: root
    mode: "0644"

- name: Render Nix flake to host
  ansible.builtin.template:
    src: flake.nix.j2
    dest: "{{ nixos_flake }}"
    mode: "0644"

- name: Perform a NixOS rebuild/switch
  ansible.builtin.command: >
    nixos-rebuild switch --flake {{ nixos_dir }}#{{ inventory_hostname }}
  register: rebuild
  changed_when: true

- name: Get current hostname
  ansible.builtin.command: hostname
  register: current_hostname
  changed_when: false
  
- name: Reboot when hostname has changed
  ansible.builtin.reboot:
    msg: "Reboot triggered after NixOS rebuild"
    connect_timeout: 10
    reboot_timeout: 1800
    pre_reboot_delay: 3
    post_reboot_delay: 10
    test_command: "whoami"
    search_paths:
      - /run/current-system/sw/bin
      - /run/wrappers/bin
      - /sbin
      - /bin
      - /usr/sbin
      - /usr/bin
      - /usr/local/sbin
  when: current_hostname.stdout != inventory_hostname
