---
aws_access_key_id: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') | default('', true) }}"
aws_default_region: "{{ lookup('env', 'AWS_DEFAULT_REGION') | default('us-east-1', true) }}"
aws_secret_access_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') | default('', true) }}"

converge_restore: true

doppler_service_token: "{{ lookup('env', 'DOPPLER_SERVICE_TOKEN_MATURIN') }}"
doppler_config: "mat"
doppler_project: "orchestrator"

source_code_repos:
  - repo: git@github.com:allan-lewis/allans-home-lab.git
    dest: allans-home-lab
    version: main
  - repo: git@github.com:allan-lewis/homelab-metrics.git
    dest: homelab-metrics 
    version: main

converge_s3_mirror: false
s3_mirror_buckets: [
  "gitops-homelab-orchestrator-disks",
  "gitops-homelab-orchestrator-haos",
  "gitops-homelab-orchestrator-tf"
]

# backup_runner_cron_minute: "20"
# backup_runner_volumes: [
#   { 
#     src: "/var/lib/allans-home-lab/s3-mirror",
#     dest: "{{ default_remote_nas_per_host_backup_volume }}/s3-mirror",
#     owner: "root"
#   }
# ]

managed_host_dirs:
  - name: s3_mirror
    local: /var/lib/allans-home-lab/s3-mirror
    remote: "{{ default_remote_nas_per_host_backup_volume }}/s3-mirror"
    owner: "root"
    group: "root"
    mode: "0755"
  - name: backup_restore_test
    local: /home/lab/backup-restore
    remote: "{{ default_remote_nas_per_host_backup_volume }}/backup-restore"
    owner: "lab"
    group: "lab"
    mode: "0755"
