---
converge_tailscale: true

doppler_service_token: "{{ lookup('env', 'DOPPLER_SERVICE_TOKEN_MATURIN') }}"
doppler_config: "mat"
doppler_project: "orchestrator"

source_code_repos:
  - repo: git@github.com:allan-lewis/allans-home-lab.git
    dest: allans-home-lab
    version: main
  - repo: git@github.com:allan-lewis/homelab-metrics.git
    dest: homelab-metrics 
    version: main

converge_s3_mirror: true
s3_mirror_buckets: [
  "gitops-homelab-orchestrator-disks",
  "gitops-homelab-orchestrator-haos",
  "gitops-homelab-orchestrator-tf"
]

managed_host_volumes:
  s3_mirror:
    type: local
    local: /var/lib/allans-home-lab/s3-mirror
    remote: "{{ default_remote_nas_per_host_backup_volume }}/s3-mirror"
    restore: true
    backup: true
    owner: "root"
    group: "root"
    mode: "0755"
  backup_restore_test:
    type: local
    local: /home/lab/backup-restore
    remote: "{{ default_remote_nas_per_host_backup_volume }}/backup-restore"
    restore: true
    backup: true
    owner: "lab"
    group: "lab"
    mode: "0755"

nixos_docker_services:
  - monitoring
