---
nixos_docker_services:
  - monitoring
  - pihole

nixos_is_virtual_machine: false
nixos_network_interface: "enp2s0"
nixos_network_address: "192.168.86.218"
nixos_ssh_key: "{{ lookup('env', 'TF_VAR_PROXMOX_VM_PUBLIC_KEY') }}"

managed_host_volumes:
  pihole_data:
    type: local
    local: "/var/lib/pihole"
    restore: false
    backup: false
    owner: "lab"
    group: "lab"
    mode: "0755"

converge_docker_pihole: true
pihole_admin_password: "{{ lookup('env', 'PIHOLE_ADMIN_PASSWORD') }}"
pihole_upstreams:
  - "1.1.1.1"
  - "1.0.0.1"
  - "9.9.9.9"
  - "149.112.112.112"
pihole_a_records:
  - name: "docker.allanshomelab.com"
    address: "192.168.86.204" 
  - name: "hosts.allanshomelab.com"
    address: "192.168.86.204" 
  - name: "media.allanshomelab.com"
    address: "192.168.86.204" 
  - name: "kvm.allanshomelab.com"
    address: "192.168.86.204"
pihole_cname_records:
  - alias: "gatus.docker.allanshomelab.com"
    target: "docker.allanshomelab.com"
  - alias: "dns.docker.allanshomelab.com"
    target: "docker.allanshomelab.com"
  - alias: "derry.hosts.allanshomelab.com"
    target: "hosts.allanshomelab.com"
  - alias: "gilead.hosts.allanshomelab.com"
    target: "hosts.allanshomelab.com"
  - alias: "pennywise.hosts.allanshomelab.com"
    target: "hosts.allanshomelab.com"
  - alias: "maturin.hosts.allanshomelab.com"
    target: "hosts.allanshomelab.com"
  - alias: "traefik.docker.allanshomelab.com"
    target: "docker.allanshomelab.com"
  - alias: "whoami.docker.allanshomelab.com"
    target: "docker.allanshomelab.com"
  - alias: "portainer.docker.allanshomelab.com"
    target: "docker.allanshomelab.com"
  - alias: "prometheus.docker.allanshomelab.com"
    target: "docker.allanshomelab.com"
  - alias: "radarr.k8s.allanshomelab.com"
    target: "k8s.allanshomelab.com"
  - alias: "sonarr.k8s.allanshomelab.com"
    target: "k8s.allanshomelab.com"
  - alias: "maturin.kvm.allanshomelab.com"
    target: "kvm.allanshomelab.com"
  - alias: "prowlarr.media.allanshomelab.com"
    target: "media.allanshomelab.com"
  - alias: "lidarr.media.allanshomelab.com"
    target: "media.allanshomelab.com"
  - alias: "bazarr.media.allanshomelab.com"
    target: "media.allanshomelab.com"
  - alias: "radarr.media.allanshomelab.com"
    target: "media.allanshomelab.com"
  - alias: "sonarr.media.allanshomelab.com"
    target: "media.allanshomelab.com"
  - alias: "jellyfin.media.allanshomelab.com"
    target: "media.allanshomelab.com"
  - alias: "transmission.media.allanshomelab.com"
    target: "media.allanshomelab.com"
  - alias: "tautulli.media.allanshomelab.com"
    target: "media.allanshomelab.com"
  - alias: "plex.media.allanshomelab.com"
    target: "media.allanshomelab.com"
  - alias: "tools.docker.allanshomelab.com"
    target: "docker.allanshomelab.com"
  - alias: "homepage.docker.allanshomelab.com"
    target: "docker.allanshomelab.com"
  - alias: "nginx.docker.allanshomelab.com"
    target: "docker.allanshomelab.com"
  - alias: "alertmanager.docker.allanshomelab.com"
    target: "docker.allanshomelab.com"
