---
nixos_docker_services:
  - immich
  - jellyfin
  - monitoring
  - plex
  - tautulli

managed_host_volumes:
  immich_db_dumps:
    type: local
    local: "/var/lib/postgres-db-dumps"
    remote: "{{ default_remote_nas_per_host_backup_volume }}/immich/db-dumps"
    restore: true
    backup: true
    owner: "root"
    group: "root"
    mode: "0755"
  immich_postgres:
    type: local
    local: "/srv/immich/postgres"
    remote: "{{ default_remote_nas_per_host_backup_volume }}/immich/postgres-volume"
    restore: true
    backup: true
    owner: "root"
    group: "root"
    mode: "0755"
  immich_redis:
    type: local
    local: "/srv/immich/redis"
    restore: false
    backup: false
    owner: "root"
    group: "root"
    mode: "0755"
  immich_model:
    type: local
    local: "/srv/immich/model-cache"
    restore: false
    backup: false
    owner: "root"
    group: "root"
    mode: "0755"
  jellyfin_config:
    type: local
    local: "/srv/jellyfin/config"
    remote: "{{ default_remote_nas_per_host_backup_volume }}/jellyfin/config"
    restore: true
    backup: true
    owner: "lab"
    group: "lab"
    mode: "0755"
  jellyfin_cache:
    type: local
    local: "/srv/jellyfin/cache"
    restore: false
    backup: false
    owner: "lab"
    group: "lab"
    mode: "0755"
  plex_config:
    type: local
    local: "/srv/plex/config"
    remote: "{{ default_remote_nas_per_host_backup_volume }}/plex/config"
    restore: true
    backup: true
    owner: "lab"
    group: "lab"
    mode: "0755"
  plex_transcode:
    type: local
    local: "/srv/plex/transcode"
    restore: false
    backup: false
    owner: "lab"
    group: "lab"
    mode: "0755"
  tautulli_config:
    type: local
    local: "/etc/tautulli"
    remote: "{{ default_remote_nas_per_host_backup_volume }}/tautulli/config"
    restore: true
    backup: true
    owner: "lab"
    group: "lab"
    mode: "0755"
  immich_upload_mount:
    type: nfs
    server: "{{ hostvars['pennywise'].ansible_host }}"
    path: "/mnt/pool1/immich"
    opts: "rw"
    restore: false
    backup: false
    local: "/data/immich"
  media_library_mount:
    type: nfs
    server: "{{ hostvars['pennywise'].ansible_host }}"
    path: "/mnt/pool1/media-library"
    opts: "ro"
    restore: false
    backup: false
    local: "/data/media-library"

converge_postgres_dump: true
postgres_db_container: immich_postgres
postgres_db_name: "immich"
postgres_db_user: "postgres"
postgres_db_password: "{{ lookup('env', 'IMMICH_DB_PASSWORD') }}"
postgres_db_backup_dir: /var/lib/postgres-db-dumps
postgres_db_extra_args: ""
