---
nixos_docker_services:
  - monitoring
  - rstack

managed_host_volumes:
  media_library_mount:
    type: nfs
    server: "{{ hostvars['pennywise'].ansible_host }}"
    path: "/mnt/pool1/media-acquisition"
    opts: "rw"
    restore: false
    backup: false
    local: "/data/media-library"
  bazarr_config:
    type: local
    local: "/etc/bazarr"
    remote: "{{ default_remote_nas_per_host_backup_volume }}/bazarr/config"
    restore: true
    backup: true
    owner: "lab"
    group: "lab"
    mode: "0755"
  lidarr_config:
    type: local
    local: "/etc/lidarr"
    remote: "{{ default_remote_nas_per_host_backup_volume }}/lidarr/config"
    restore: true
    backup: true
    owner: "lab"
    group: "lab"
    mode: "0755"
  prowlarr_config:
    type: local
    local: "/etc/prowlarr"
    remote: "{{ default_remote_nas_per_host_backup_volume }}/prowlarr/config"
    restore: true
    backup: true
    owner: "lab"
    group: "lab"
    mode: "0755"
  radarr_config:
    type: local
    local: "/etc/radarr"
    remote: "{{ default_remote_nas_per_host_backup_volume }}/radarr/config"
    restore: true
    backup: true
    owner: "lab"
    group: "lab"
    mode: "0755"
  sonarr_config:
    type: local
    local: "/etc/sonarr"
    remote: "{{ default_remote_nas_per_host_backup_volume }}/sonarr/config"
    restore: true
    backup: true
    owner: "lab"
    group: "lab"
    mode: "0755"
  transmission_config:
    type: local
    local: "/etc/transmission"
    remote: "{{ default_remote_nas_per_host_backup_volume }}/transmission/config"
    restore: true
    backup: true
    owner: "lab"
    group: "lab"
    mode: "0755"
  transmission_watch:
    type: local
    local: "/var/lib/transmission/watch"
    remote: "{{ default_remote_nas_per_host_backup_volume }}/transmission/watch"
    restore: false
    backup: false
    owner: "lab"
    group: "lab"
    mode: "0755"

