background {
    monitor =
    path = /home/lab/wallpapers/default.png
    blur_passes = 2
    blur_size = 5
}

label {
    monitor =
    text = $TIME
    font_family = JetBrainsMono Nerd Font
    font_size = 64
    color = @LOCK_TIME@
    position = 0, 520
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 280, 56
    position = 0, 420
    halign = center
    valign = center

    font_family = JetBrainsMono Nerd Font
    font_color = @LOCK_INPUT_TEXT@

    inner_color = @LOCK_INPUT_INNER@
    outer_color = @LOCK_INPUT_OUTER@
    check_color = @LOCK_INPUT_CHECK@
    fail_color = @LOCK_INPUT_FAIL@

    outline_thickness = 3
    rounding = 12
    fade_on_empty = true

    placeholder_text = enter password
    fail_text = password incorrect
}