$mod = SUPER
$terminal = ghostty
$launcher = wofi --show drun
$editor = codium

exec-once = waybar
exec-once = mako
exec-once = hyprpaper
exec-once = hypridle
exec-once = ${pkgs.polkit_gnome}/libexec/polkit-gnome-authentication-agent-1

bind = $mod, C, exec, $editor
bind = $mod, RETURN, exec, $terminal
bind = $mod, D, exec, $launcher
bind = $mod, Q, killactive
bind = $mod, B, exec, google-chrome-stable
bind = $mod, Q, killactive
bind = $mod SHIFT, E, exit
bind = $mod, F, fullscreen
bind = $mod SHIFT, F, togglefloating

bind = $mod, H, movefocus, l
bind = $mod, L, movefocus, r
bind = $mod, K, movefocus, u
bind = $mod, J, movefocus, d

bind = $mod SHIFT, H, swapwindow, l
bind = $mod SHIFT, L, swapwindow, r
bind = $mod SHIFT, K, swapwindow, u
bind = $mod SHIFT, J, swapwindow, d

binde = SUPER, minus, resizeactive, -40 0
binde = SUPER, equal, resizeactive, 40 0
binde = SUPER SHIFT, minus, resizeactive, 0 -40
binde = SUPER SHIFT, equal, resizeactive, 0 40

bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3

bindm = $mod, mouse:272, movewindow
bindm = $mod, mouse:273, resizewindow

bind = , XF86AudioRaiseVolume, exec, pactl set-sink-volume @DEFAULT_SINK@ +5%
bind = , XF86AudioLowerVolume, exec, pactl set-sink-volume @DEFAULT_SINK@ -5%
bind = , XF86AudioMute, exec, pactl set-sink-mute @DEFAULT_SINK@ toggle

# Switch to workspace
bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5
bind = $mod, 6, workspace, 6
bind = $mod, 7, workspace, 7
bind = $mod, 8, workspace, 8
bind = $mod, 9, workspace, 9

# Move window to workspace
bind = $mod SHIFT, 1, movetoworkspace, 1
bind = $mod SHIFT, 2, movetoworkspace, 2
bind = $mod SHIFT, 3, movetoworkspace, 3
bind = $mod SHIFT, 4, movetoworkspace, 4
bind = $mod SHIFT, 5, movetoworkspace, 5
bind = $mod SHIFT, 6, movetoworkspace, 6
bind = $mod SHIFT, 7, movetoworkspace, 7
bind = $mod SHIFT, 8, movetoworkspace, 8
bind = $mod SHIFT, 9, movetoworkspace, 9

# ---- SCREENSHOTS ----

# Full screen → file
bind = SUPER, S, exec, grim ~/Pictures/screenshot-$(date +%s).png

# Region select → file
bind = SUPER SHIFT, S, exec, grim -g "$(slurp)" ~/Pictures/screenshot-$(date +%s).png

# Region select → clipboard
bind = SUPER CTRL, S, exec, grim -g "$(slurp)" - | wl-copy

bind = SUPER CTRL, L, exec, hyprlock