name: callahan
hostname: callahan

platform: linux
variant: arch

role: tinker
description: Arch Sandbox, BTW

groups:
  - arch

management:
  provisioner: terraform
  converger: ansible

runtime:
  kind: vm
  hypervisor: proxmox
  node: maturin

resources:
  cpu:
    cores: 4
    sockets: 1
  memory_mb: 4096
  disk_gb: 32

network:
  mode: static
  ipv4:
    address: 192.168.86.214
    gateway: 192.168.86.1
  dns:
    - 192.168.86.1

provisioning:
  terraform:
    cloud_init: true
    agent: true
