---
all:
  hosts:
    barlow:
      ansible_host: 192.168.86.213
      gatus_slug: "(Ubuntu Sandbox)"
      observability: false
      prometheus_scrape_jobs:
        node-exporter: [9100]
        homelab-metrics: [9102]
    blaine:
      ansible_host: 192.168.86.223
      gatus_slug: "(OpenVPN Gateway)"
      prometheus_scrape_jobs:
        node-exporter: [9100]
    callahan:
      ansible_host: 192.168.86.214
      gatus_slug: "(Arch Sandbox, BTW)"
      observability: false
      prometheus_scrape_jobs:
        node-exporter: [9100]
        homelab-metrics: [9102]
    carrie:
      ansible_host: 192.168.86.228
      gatus_slug: "(NixOS Apps)"
      prometheus_scrape_jobs:
        node-exporter: [9100]
        homelab-metrics: [9102]
    christine:
      ansible_host: 192.168.86.212
      gatus_slug: "(Windows 11)"
    cujo:
      ansible_host: 192.168.86.219
      gatus_slug: "(NixOS DevOps)"
      prometheus_scrape_jobs:
        node-exporter: [9100]
        homelab-metrics: [9102]
    derry:
      ansible_host: 192.168.86.210
      gatus_slug: "(Local Backup)"
      prometheus_scrape_jobs:
        node-exporter: [9100]
    flagg:
      ansible_host: 192.168.86.204
      gatus_slug: "(NixOS Core)"
      prometheus_scrape_jobs:
        cloudflare: [2000]
        gatus: [8080]
        node-exporter: [9100]
        homelab-metrics: [9102]
    gan:
      ansible_host: 192.168.86.211
      gatus_slug: "(MacOS)"
    gilead:
      ansible_host: 100.95.108.6
      gatus_slug: "(Remote Backup)"
      prometheus_scrape_jobs:
        node-exporter: [9100]
    langolier:
      ansible_host: 192.168.86.218
      gatus_slug: "(NixOS Pi-hole)"
      prometheus_scrape_jobs:
        node-exporter: [9100]
        homelab-metrics: [9102]
    maturin:
      ansible_host: 192.168.86.200
      gatus_slug: "(Proxmox Hypervisor)"
      prometheus_scrape_jobs:
        node-exporter: [9100]
    misery:
      ansible_host: 192.168.86.227
      gatus_slug: "(NixOS Media)"
      prometheus_scrape_jobs:
        node-exporter: [9100]
        homelab-metrics: [9102]
    mordred:
      ansible_host: 192.168.86.206
      gatus_slug: "(Retro Gaming)"
      prometheus_scrape_jobs:
        node-exporter: [9100]
    overlook:
      ansible_host: 192.168.86.229
      gatus_slug: "(Home Automation)"
      prometheus_scrape_jobs:
        node-exporter: [9100]
    patricia:
      ansible_host: 192.168.86.224
      gatus_slug: "(NixOS R Stack)"
      prometheus_scrape_jobs:
        node-exporter: [9100]
        homelab-metrics: [9102]
    pennywise:
      ansible_host: 192.168.86.220
      gatus_slug: "(NAS)"
      prometheus_scrape_jobs:
        node-exporter: [9100]
    roland:
      ansible_host: 192.168.86.207
      gatus_slug: "(Arch Desktop, BTW)"
      observability: false
      prometheus_scrape_jobs:
        node-exporter: [9100]
    todash:
      ansible_host: 192.168.86.216
      gatus_slug: "(NixOS Sandbox)"
      observability: false
      prometheus_scrape_jobs:
        node-exporter: [9100]
        homelab-metrics: [9102]

  children:
    arch:
      children:
        arch_docker:
          children:
            arch_tinker:
              hosts:
                callahan:

    nixos:
      children:
        nixos_docker:
          children:
            nixos_apps:
              hosts:
                carrie:
            nixos_core:
              hosts:
                flagg:
            nixos_devops:
              hosts:
                cujo:
            nixos_media:
              hosts:
                misery:
            pixos_pihole:
              hosts:
                langolier:
            nixos_rstack:
              hosts:
                patricia:
            nixos_tinker:
              hosts:
                todash:
            nixos_twingate:
              hosts:
                carrie:
                flagg:

    ubuntu:
      children: 
        ubuntu_docker:
          children:
            ubuntu_tinker:
              hosts:
                barlow:
        ubuntu_openvpn:
          hosts:
            blaine:
