doppler_token: ENC[AES256_GCM,data:4g0BOYK0Pt5Ct/NMT1t9OY+GRonwT2zQrkS/hUJMkLb7luDTeS0nd5jLnhyevhDy4kRKXCpe,iv:mySFui58E+VZ9TyZfC2S14QOIHw5TVj+sntVMO5CBzM=,tag:8XzwcX5sBE9BF/Iskh01lQ==,type:str]
sops:
    age:
        - recipient: age1rsa3wqfhq3fxjmkqf3809wln39f64qvlqgwxy4usx9jng7t545xs8ts3dp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5M1ZZbGg2UDV5MHkrNEF1
            VGJ6NE9vUzlIaXRxWHo2OFFML0drR3QwUlZjCkRWK0JtdUFzbWI2aVZ6Y2FaT2Rp
            c0RiY1pGMGpUTlIrdGFkL2c3NFhDbjQKLS0tICtNMlFKUEpZRmhYcm4xMVMwYi85
            R2RkNDJxNkIyRVQ1QWxQM1RoclZlMkUKi4l9iOLaaGWzzkkTkk1ON7KDfk+Y2A0f
            4YsNAjQY1m+IbEyyU1Bl9CHr/fIMNUCAEQWwkYoRd4S/Ef68h7bVDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-13T19:03:29Z"
    mac: ENC[AES256_GCM,data:RX8hktuMG1BKicHnBtcErH/cRirrHoV+wb4iFoo4AYlqKYJf3cfQl3eLnFMSJrOaNcl1FA6Yz3uR35f7VGHZFpew48seELb0NU8K9tFNi32gPn22G8kt5E3Trc94nJlyJA4G9xjP3DiQ0E2kBbt77hddfFhgdxlyTgKs6KH3+Qk=,iv:XLKyLNAnYDX0+hABbGaFoXGK/bmexxslx8tk3O/mGnU=,tag:S60KhLRge2kOHkt5HNc9Ag==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
