---
- name: Restrict allowed ssh users.
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^AllowUsers'
    line: 'AllowUsers {{ ansible_user }}'
    state: present

- name: Disable root login access.
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^(#)?PermitRootLogin \w*$'
    line: 'PermitRootLogin no'
    state: present

- name: Disable SSH password authentication.
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^#?\s*PasswordAuthentication\s'
    line: 'PasswordAuthentication no'
    state: present

- name: Update SSH host key algorithms.
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: 'HostKeyAlgorithms'
    line: 'HostKeyAlgorithms +ssh-rsa'
    state: present

- name: Update SSH public key accepted algorithms.
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: 'PubkeyAcceptedAlgorithms'
    line: 'PubkeyAcceptedAlgorithms +ssh-rsa'
    state: present
