---
- name: Install cronie
  community.general.pacman:
    name: cronie
    state: present
    update_cache: true

- name: Enable and start cronie
  ansible.builtin.systemd:
    name: cronie
    enabled: true
    state: started

- name: Ensure resolv.conf contains sane DNS servers
  ansible.builtin.copy:
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: "0644"
    content: |
      # Managed by Ansible - linux_services role
      nameserver 192.168.86.1
      nameserver 1.1.1.1
      nameserver 8.8.8.8