---
- name: REHYDRATE | Rehydrate managed directories
  become: true
  ansible.builtin.command: >
    rehydrate-managed-dirs homelab-task-managed-dirs-rehydrate.service
  changed_when: false
  when: converge_restore | bool
  tags: [finalize, finalize_rehydrate]

- name: REPOS | Check out GitHub repos
  become: true
  ansible.builtin.command:
    cmd: systemctl start homelab-task-dev_checkouts_sync.service
  when: converge_devops | bool
  tags: [finalize, finalize_repos]
