---
- name: Ensure node_exporter textfile collector directory exists
  become: true
  ansible.builtin.file:
    path: /var/lib/node_exporter/textfile_collector
    state: directory
    owner: root
    group: root
    mode: "0755"
  when: converge_docker_monitoring

- name: Monitoring | Deploy Docker compose app
  ansible.builtin.include_role:
    name: converge_linux_docker_compose
  vars:
    compose_app_name: monitoring
    compose_source_type: template
    compose_template_src: "templates/monitoring.compose.yaml.j2"
  when: converge_docker_monitoring

