CLOUDFLARE_API_KEY: ENC[AES256_GCM,data:eTnOYCNDKh8GgwLal1T7bMHuJuodlrJKy7WTg3VY7Jv2Wa0/gQ==,iv:40g1A+ewLMLcdNkXG61HzDwG+rRMEcUd1YCw1I3ws3Y=,tag:om4aqObgrhDcL0m9owdR9w==,type:str]
sops:
    age:
        - recipient: age1rsa3wqfhq3fxjmkqf3809wln39f64qvlqgwxy4usx9jng7t545xs8ts3dp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoVTJ6T0VEOU9sWnV1dUU0
            clArYjN2a3Z2azRoUUtBM2lJYnhBNVI2THpZCmJpMHBjc2RTV3hpTlZPS3FSd2ZQ
            ZVUzVVpES0FodmtoMlcyRURWcEwrQWsKLS0tIFV0dFVOU2l0TDFYUk5lZHA0dUZx
            OFk1N2N0enVIeGUxQTdIMU5FV0o0MEEK0PChYV6kfjwP26y6t5mBTzwanbMIxv0Y
            7WGm0sOZ4yygYDISkXhg+rwnTZ27B/Efxg7TZXTnPDKV6Jxba7t7IA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T20:32:34Z"
    mac: ENC[AES256_GCM,data:J6pOM4G58fjf+k7qsyAxADVB5Zy5yezPnK/kl2NuIKmbFM9RR3YAG69XtaRpyzwVy7DS/ZsjXO02D0cUHuX5l/5VAEpGb4/JeXLtIeDnZ89aWzM1R3zIzU4vjZip5syqyfPR5vEBGjJojgnOjrpZL1b9MtYDR3TsF28zuRGkg1Q=,iv:E1VzKKcgXADUd9KD2XZebVD8KnfB+vBuaLBdM72ngMs=,tag:OQcpRhZ5H3ALyXSCoidGrA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
