---
- name: Full Linux host convergence for a group of hosts
  hosts: "{{ converge_group }}"
  gather_facts: true
  become: true

  tasks:
    - name: Ping to verify connectivity
      ansible.builtin.ping:
      when: converge_arch or converge_ubuntu
      tags: [ping, ubuntu_base, ubuntu_harden, ubuntu_docker, ubuntu_openvpn, linux_shell, linux_monitoring, linux_node_exporter, arch_sanity, arch_base, arch_harden, arch_services, arch_docker]

    - name: Perform Arch sanity checks
      ansible.builtin.include_role:
        name: converge_arch_sanity
        apply:
          tags: [arch_sanity]
      when: converge_arch
      tags: [arch_sanity]

    - name: Perform base Arch setup
      ansible.builtin.include_role:
        name: converge_arch_base
        apply:
          tags: [arch_base]
      when: converge_arch
      tags: [arch_base]

    - name: Perform Arch hardening steps
      ansible.builtin.include_role:
        name: converge_arch_harden
        apply:
          tags: [arch_harden]
      when: converge_arch
      tags: [arch_harden]

    - name: Install Arch services
      ansible.builtin.include_role:
        name: converge_arch_services
        apply:
          tags: [arch_services]
      when: converge_arch
      tags: [arch_services]

    - name: Perform Arch Docker setup
      ansible.builtin.include_role:
        name: converge_arch_docker
        apply:
          tags: [arch_docker]
      when: converge_arch and converge_docker
      tags: [arch_docker]

    - name: Perform base Ubuntu setup
      ansible.builtin.include_role:
        name: converge_ubuntu_base
        apply:
          tags: [ubuntu_base]
      when: converge_ubuntu
      tags: [ubuntu_base]

    - name: Perform Ubuntu hardening steps
      ansible.builtin.include_role:
        name: converge_ubuntu_harden
        apply:
          tags: [ubuntu_harden]
      when: converge_ubuntu
      tags: [ubuntu_harden]

    - name: Perform Ubuntu Docker setup
      ansible.builtin.include_role:
        name: converge_ubuntu_docker
        apply:
          tags: [ubuntu_docker]
      when: converge_ubuntu and converge_docker
      tags: [ubuntu_docker]

    - name: Setup the user's KSH shell
      ansible.builtin.include_role:
        name: converge_linux_shell
        apply:
          tags: [linux_shell]
      when: converge_ubuntu or converge_arch
      tags: [linux_shell]

    - name: Install Docker monitoring services
      ansible.builtin.include_role:
        name: converge_linux_monitoring
        apply:
          tags: [linux_monitoring]
      when: (converge_arch or converge_ubuntu) and converge_docker_monitoring
      tags: [linux_monitoring]

    - name: Install Node Exporter
      ansible.builtin.include_role:
        name: converge_linux_node_exporter
        apply:
          tags: [linux_node_exporter]
      when: (converge_arch or converge_ubuntu) and feature_flag_node_exporter
      tags: [linux_node_exporter]

    - name: Setup Ubuntu OpenVPN gateway host(s)
      ansible.builtin.include_role:
        name: converge_ubuntu_openvpn
        apply:
          tags: [ubuntu_openvpn]
      when: converge_ubuntu and feature_flag_openvpn
      tags: [ubuntu_openvpn]
