---
- name: Full NixOS host convergence for a group of hosts
  hosts: "{{ converge_group }}"
  become: true
  gather_facts: true

  tasks:
    - name: Prepare host(s) for convergence
      ansible.builtin.include_role:
        name: converge_nixos_prepare
      when: converge_nixos | default(false) | bool
      tags: [prepare, prepare_vars, prepare_groups, prepare_dirs, prepare_files, prepare_keys, prepare_dotfiles, prepare_aws, prepare_tailscale, prepare_dump, prepare_doppler]

    - name: Update configs and rebuild host(s)
      ansible.builtin.include_role:
        name: converge_nixos_rebuild
      when: converge_nixos | default(false) | bool
      tags: [rebuild, rebuild_hw, rebuild_modules, rebuild_flake, rebuild_switch]

    - name: Finish any remaining host setups following rebuild
      ansible.builtin.include_role:
        name: converge_nixos_finalize
      when: converge_nixos | default(false) | bool
      tags: [finalize, finalize_rehydrate, finalize_repos, finalize_doppler]

    - name: Deploy Docker Compose services
      ansible.builtin.include_role:
        name: converge_nixos_docker
      vars:
        compose_config: "{{ nixos_docker_service_configs[item] }}"
      when:
        - converge_nixos | default(false) | bool
        - converge_docker | default(false) | bool
      tags: [docker]
      with_items: "{{ nixos_docker_services | default([]) }}"
