client
dev tun0
fast-io
persist-key
persist-tun
nobind

remote uk-east-london-ca-version-2.expressnetw.com 1195
remote-random

pull
comp-lzo no

tls-client
verify-x509-name Server name-prefix
remote-cert-tls server

key-direction 1

route-delay 2
tun-mtu 1500
fragment 1300
mssfix 1200

verb 3

cipher AES-256-GCM
auth SHA512

sndbuf 524288
rcvbuf 524288

auth-user-pass /run/secrets/openvpn/auth.txt
cert /run/secrets/openvpn/client.crt
key /run/secrets/openvpn/client.key
tls-auth /run/secrets/openvpn/tls-auth.key
ca /run/secrets/openvpn/ca.crt